name: CelestCombat-Pro
version: '1.2.0'
main: com.shyamstudio.celestCombatPro.CelestCombatPro
api-version: '1.21'
authors: [ RaviRai, Nighter, WeThink ]
description: A simple combat logging plugins
folia-supported: true

soft-depend:
  - WorldGuard
  - Multiverse-Core
  - Worlds
  - PlaceholderAPI

commands:
  celestcombat:
    description: Main command for CelestCombat
    usage: /celestcombat
    aliases: [cc, combat]

permissions:
  celestcombat.command.use:
    description: Allows players to use all commands of CelestCombat
    default: op
  celestcombat.update.notify:
    description: Allows players to receive update notifications
    default: op
  celestcombat.bypass.tag:
    description: Allows players to bypass being tagged in combat
    default: false